### ISSUE TITLE
Niaje Peter

### ISSUE THREAD

**Issue by simonjenga** [pmaingi/auction_manager#1]

**Comment by pmaingi** [comment]
Poa sana..ur too lost..haupatikani..even on skype

**Comment by simonjenga** [comment]
@pmaingi Poa sana, mimi tu niko poa. Mimi hutokea online kwa Skype Ma interviews ndio kibao.

**Comment by pmaingi** [comment]
bado uko freelance or ulipata place nyingine..

2016-02-08 13:00 GMT+03:00 Simon N. <notifications@github.com>:

> @pmaingi <https://github.com/pmaingi> Poa sana, mimi tu niko poa. Mimi
> hutokea online kwa Skype Ma interviews ndio kibao.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pmaingi/auction_manager/issues/1#issuecomment-181283611>
> .
>



-- 
pmaingi@gmail.com

Tel: 254 720 244970
No man in the world has more courage than the man who can stop after eating
one peanut.

**Comment by simonjenga** [comment]
@pmaingi Nimeingia Skype

**Comment by pmaingi** [comment]
ok..niko online

On Mon, Feb 8, 2016 at 1:17 PM, Simon N. <notifications@github.com> wrote:

> @pmaingi <https://github.com/pmaingi> Nimeingia Skype
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pmaingi/auction_manager/issues/1#issuecomment-181292468>
> .
>



-- 
pmaingi@gmail.com

Tel: 254 720 244970
No man in the world has more courage than the man who can stop after eating
one peanut.

**Comment by simonjenga** [comment]
@pmaingi Hi, Siku-weza-make jana, kuli nyesha tu sana.
Will be online via Skype shortly...

**Comment by pmaingi** [comment]
ok..mimi niko skype

On Tue, Feb 9, 2016 at 4:48 PM, Simon N. <notifications@github.com> wrote:

> @pmaingi <https://github.com/pmaingi> Hi, Siku-weza-make jana, kuli
> nyesha tu sana.
> Will be online via Skype shortly...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pmaingi/auction_manager/issues/1#issuecomment-181870870>
> .
>



-- 
pmaingi@gmail.com

Tel: 254 720 244970
No man in the world has more courage than the man who can stop after eating
one peanut.
